### ISSUE TITLE
Forget Notebook

### ISSUE THREAD

**Issue by Iznik285** [dvorka/mindforger#1296]
Windows 10 / MF 1.52.0

To forget a notebook, you currently need to enter the notebook and then click on Notebook / Forget.
I think it would be cleaner to forget a notebook from the  View / Notebooks (Ctrl-Shift-O) screen.

A minor issue but it allows for consistency with the forgetting notes option.

**Comment by dvorka** [comment]
Actually it's intentional - I wanted to make sure that user exactly knows what will be forgotten. Notebooks may have the same names and we do mistakes. There is no undo (in UI) for forget action (however, Notebook is never deleted, it's just moved to `limbo` directory on the filesystem).

I agree that it might be inconsistent with the other actions, however, it's about safety...

**Comment by Iznik285** [comment]
I can see that and it makes sense. My preference was to use the "are you sure" dialog box and also prefer the idea that when you are in a note you cannot forget it. Happy to close the issue following your explanation
