### ISSUE TITLE
Certificate verification error with Debian repo public key

### ISSUE THREAD

**Issue by wordpressjeff** [dvorka/mindforger#1352]
added repo and key:

```
# add PPA to APT sources:
sudo bash -c 'echo -e "\ndeb https://www.mindforger.com/debian stretch main" > /etc/apt/sources.list.d/mindforger.list'

# import PPA's GPG key
wget -qO - http://www.mindforger.com/gpgpubkey.txt | sudo apt-key add -

# update sources
sudo apt update
```

error on apt update:

```
Err:9 https://www.mindforger.com/debian stretch Release                                                       
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 93.185.104.33 443
```]

**Comment by dvorka** [comment]
@wordpressjeff I successfully tested the installation on clean Debian installation. The root cause of the failure might be your local system configuration (more strict), also PPA currently has packages for old `stretch` release only (you may want to check GitHub releases page to get .deb for BullsEye ~ at least initial installation).

**Comment by wordpressjeff** [comment]
@dvorka I can also confirm this is no longer an issue. My Bullseye install is squeaky clean now (it may not have been then) and the repo plays nice. I'll grab a .deb from GitHub, thanks for the nudge 👍
