### ISSUE TITLE
Can't install on Kubuntu?

### ISSUE THREAD

**Issue by samuel-l-schmidt** [dvorka/mindforger#1379]
I am running the latest Kubuntu version. 
I followed the installation guide for ubuntu. 
Unfortunaly, after 
`sudo add-apt-repository ppa:ultradvorka/productivity`
I get: 
```
E: The "http://ppa.launchpad.net/ultradvorka/productivity/ubuntu focal Release" depot does not contain a release file.
N: Updating from such a depot cannot be done in a safe way, so it is disabled by default.
```
and later: 
`E: Package mindforger cannot be found.`

Any help is appreciated. 
`

**Comment by gstalnaker** [comment]
samuel-l-schmidt - because dvorka is behind on ubuntu releases, there will be no 'focal' release. When I encounter this kind of thing (which I did for mindforge), I use the Repositories part of Synaptic (yep, I still use Synaptic) where I can edit the repository directly and specify a release). This is exactly what I had to do here. My repository config for mindforger is:
Type: deb
URI: http://ppa.launchpad.net/ultradvorka/productivity/ubuntu/
Distribution: disco
Section(s): main
And that worked for me.

**Comment by dvorka** [comment]
@samuel-l-schmidt @gstalnaker  Apologies for being so behind! I added MindForger 1.52.0 release for Ubuntu Focal Fossa, Hirsute Hippo and Impish Indri to Launchpad PPA - check https://launchpad.net/~ultradvorka/+archive/ubuntu/productivity/+packages
