### ISSUE TITLE
Strange display of "time" 

### ISSUE THREAD

**Issue by BNortonnul** [dvorka/mindforger#1388]
In the notebook's properties panel, "Importance" looks like this...
![mindforger_jtWYuJ2G50](https://user-images.githubusercontent.com/23107982/141870229-b91e1d12-79cd-4a11-9557-66f8108612ab.png)

But "Urgency" looks like this:
![mindforger_WyoAa0igkH](https://user-images.githubusercontent.com/23107982/141870227-efc2bd89-fe76-4977-896f-9abdab4d0140.png)

Not sure what's going on there, but it isn't right.

**Comment by dvorka** [comment]
@BNortonnul thank you for the bug report, Windows, right?

**Comment by BNortonnul** [comment]
Yep, Windows 10 x64

**Comment by dvorka** [comment]
Status: not reproducible on 37a2547c99b8a70e31f96402fd9afdd7b27e6014 (1.53.0 WIP), Win 10.

**Comment by Iznik285** [comment]
I am using MF 1.53.419 (af9be2f1) on Windows 10 - 20H2

Assuming the issue is referring to the look of the icons under urgency, I am seeing the same as originally reported. Under notebook properties:

Importance:

![image](https://user-images.githubusercontent.com/63961864/147340070-65a11529-73ca-4c1d-bdd8-87b57941a22e.png)

Urgency:

![image](https://user-images.githubusercontent.com/63961864/147340107-04b97e75-aab9-439b-a8e8-c7db6543f3ff.png)

**Comment by dvorka** [comment]
Oh, :ok_hand: - I will try to find a better unicode characters which won't look that ugly. If you would have any suggestion, I will be happy to use it!

**Comment by dvorka** [comment]
Fixed: it's stupid and ugly, but due to poor Unicode (font) support on Windows, macOS and certain Linux distros (like Fedora) I had to change clock character to diamond in 4a3298d which will hopefully work everywhere.
