### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by jasper-zanjani** [dvorka/mindforger#1412]
I have been trying to use Mindforger for a few weeks, and one of the "papercut" issues that has been bothering me is that the default keyboard shortcuts cannot be changed (as far as I know). More support for custom keyboard shortcuts would allow people to adjust to the application more quickly from whatever they're currently using. 

Here are some suggestions for new default keyboard shortcuts:
- <kbd>Ctrl+N</kbd> create a new Note
- <kbd>/</kbd> focus on the search bar.

The editor as well should support additional keyboard shortcut functionality:
- <kbd>Esc</kbd> exit editor
- <kbd>Ctrl+S</kbd> save
- <kbd>Ctrl+B</kbd> (bold) surround with `**`
- <kbd>Ctrl+I</kbd> (italic) surround with `*` or `_`
- When text is selected, <kbd>(</kbd>, <kbd>[</kbd>, <kbd>{</kbd>, <kbd>&lt;</kbd>, <kbd>`</kbd>, <kbd>'</kbd>, or <kbd>"</kbd> should surround the selection with appropriate characters instead of overwriting.

**Comment by stexyz** [comment]
👍

**Comment by dvorka** [comment]
Progress:

- [x] <kbd>Ctrl+N</kbd> create a new Note
- [ ] <kbd>/</kbd> focus on the search bar.
- [ ] <kbd>Esc</kbd> exit editor
- [x] <kbd>Ctrl+S</kbd> save
- [x] <kbd>Ctrl+B</kbd> (bold) surround with `**`
- [x] <kbd>Ctrl+I</kbd> (italic) surround with `*` or `_`
- [ ] When text is selected, <kbd>(</kbd>, <kbd>[</kbd>, <kbd>{</kbd>, <kbd>&lt;</kbd>, <kbd>`</kbd>, <kbd>'</kbd>, or <kbd>"</kbd> should surround the selection with appropriate characters instead of overwriting.

**Comment by dvorka** [comment]
@jasper-zanjani @quesada @stexyz all shortcuts listed above will be released with 1.54.0 (except <kbd>/</kbd> for search - if you insist on adding it, please specify platform and open new GitHub issue).
