### ISSUE TITLE
Segfault when cloning a large awesomel list

### ISSUE THREAD

**Issue by QuinnNguyen** [dvorka/mindforger#671]
Segfault happen when trying clone big repos. I manage to work around the issue by migrating the doc manually instead

**Comment by dvorka** [comment]
@QuinnNguyen thank you for reporting this critical issue. In order to fix it I would like to kindly ask you for a hint how I can reproduce it (BTW I'm going to release a new MF version very soon w/ a number of fixes in runtime and Markdown parser):

* Can you please clarify what you mean by "clone" big repos? Notebooks and/or Notes can be cloned in MindForger (from menu), but I don't exactly understand which operation do you mean by this...
* Which operating system/version/distribution do you use? Did you compiled MindForger or downloaded an archive? (`uname -a`, `lsb_release -a`, ...)
* Can you please run and crash MF with `strace` and attach/paste log to this issue? `strace mindforger > mf-log.txt 2>&1` (just in case you have still chance to do that)
* Would you have a coredump file? (if so, I would need also exact OS/distro specification)

Thank you for the submissions and your interest in MindForger! (in case that you don't have time/resources to reproduce the issue it's obviously OK).

**Comment by QuinnNguyen** [comment]
1. Based on one example of MF used as IDE; I thought i can somehow clone the .md files to my own mf-repos and adding existed tag within my own knowledge base
2. Yes, you can use your examples in user manual (MF as IDE) and then open Notebook, click Clone.
3. I use manjaro linux. I test this on both the aur package and your nightly build version; the issue seem persist
4. [mf-log](https://paste.city/32) 

I'm a long time zotero user trying to re-centralized my own knowledge base; i have trying in and out so many apps and MF is the first application that I found super amusing (in both concept and the implementation). Judging from the nightly build (well technically now your lastest release), i think you are heading to create a much better, lighter and cleaner implementation of [Connected Text](http://www.connectedtext.com/)? My major interest is stats so the AI oriented side of MF catch my interest as well. I'm happy to help MF, it is has its flaw but thank you on working almost non-stop to fix the bugs.

**Comment by QuinnNguyen** [comment]
actually I retest and find out it is not depend on the repos. But the issue happen only when you trying to clone the document itself. To be specific, you can open any notebook, click on title. Then click on Notebook -> Clone -> I got segfault

**Comment by dvorka** [comment]
**Segmentation Fault**: Perfect! I was able to reproduce it! Thanks - this really helped!

**Zotero and ConnectedText**: actually I was not aware of these applications until a few days ago (when other user(s) suggested me to check them). 

> i think you are heading to create a much better, lighter and cleaner implementation of Connected Text

You are right - I just checked ConnectedText web and I think that it's basically (better) implementation of MindForger's predecessor [MindRaider](https://www.google.cz/search?q=mindraider&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjTwMnSt5fcAhWHxaYKHYgkAjQQ_AUICigB&biw=1360&bih=646) that I did 10 years ago. As you mentioned in your comment - I want to achieve more with MindForger - get beyond a note taking tool. What you see today is just a foundation - I have a vision and I hope that I (and community) will be able to make it reality. Next step is AI, NLP, NER, RNN, word embeddings, ... verified on science papers domain (to solve problems and measure quality). But there is much more exciting problems and features to deliver thinking notebook one day.

**Comment by dvorka** [comment]
BTW I checked ConnectedText once again - it is very similar to MindRaider that I released in 2004 under GPL http://mindraider.sourceforge.net/gallery/mindraider-incubator/index.html

ConnectedText is closed source commercial application written in the same programming language and using same libraries (knowledge graph)... I have some doubts :-/

**Comment by QuinnNguyen** [comment]
then definitely you can warn their current user base. Most note taker enthusiast or researcher are actually paying for this barely maintained software because of the lack of alternative.

**Comment by dvorka** [comment]
Fix will be released w/ next MF version.
