### ISSUE TITLE
Why don't you keep standard keyboard shortcuts?

### ISSUE THREAD

**Issue by waldauf** [dvorka/mindforger#783]
Hello Martin,

at first thanks for your work. I found out this project and really like it. :+1: 

Can I ask you why you don't keep standard keyboard shortcuts for save file, bold text, links, ... ? I'm asking because it's little bit confused to learn new shortcuts. :]

**Comment by dvorka** [comment]
@waldauf the answer is twofold: 

* I'm Emacs user (<kbd>Ctrl</kbd><kbd>b</kbd> moves cursor backward, <kbd>Ctrl</kbd><kbd>s</kbd> searches the document forward, ...), therefore *standard* has slightly different meaning for me.
* I would like to provide platform/editor specific key binding (Windows/Emacs/Vim/...). There is even configuration option in `File/Preferences/Markdown/Editor`, however, it does almost nothing. It's because I'm busy with other features and this one is of low priority (#191, #552). 

Please stay tuned - I would like to deliver this feature sooner or later (perhaps a contributor will help).

I really appreciate your feedback. Thank you for you interest in MindForger!

**Comment by waldauf** [comment]
@dvorka: You're right. I realized that everyone has different standard. For me is natural to use VIm's shortcuts (visual/insert mode, ctrl+/ for search, shift+g, gg, ... ). So now I understand to you. Thx for your answer.

I discovered possibility to change Editor key binding but as you wrote - it did nothing.

**Comment by dvorka** [comment]
@waldauf Thank you for the feedback and interest in MindForger - I will give key bindings related issues higher priority.

**Comment by toprak** [comment]
@dvorka does mindforger give vim keybindings?

**Comment by waldauf** [comment]
@toprak [here](https://github.com/dvorka/mindforger/issues/191#issuecomment-417769117) You can find out more about VIm keybindings.
