### ISSUE TITLE
MindForger crashes when SCROLLING longer notes HTML preview

### ISSUE THREAD

**Issue by sbstn87** [dvorka/mindforger#995]
Hi,

on Windows, each time I open a long note, or create a new one that is longer than a few lines, MindFoger crashes. Here's my screen recording showing the issue:
https://i.imgur.com/JUIsR46.gifv

When I move the cursor I try to click, but the application has stopped responding after opening the note.

Regards

**Comment by dvorka** [comment]
Thank you for reporting the problem! Can you please more precisely describe **when** you click - is it click or double click in HTML preview? Did you click entry in associations (bottom left corner)? Does MF simply dies after some time?

Also, could you please share more details about your system? Which version of Microsoft Windows do you have?

The reason why I'm asking is that I need to *reproduce* the problem so that I can fix it. Thank you for all your help!

**Comment by dvorka** [comment]
Reproducible by @vlastahajek - root cause is **scrolling** on Ns which are bigger than one page.

**Comment by sbstn87** [comment]
I confirm that the the issue is caused by scrolling, that is why only long notes crash MindForger.

**Comment by dvorka** [comment]
Reproducibility:
* reproducible on ... by @sbstn87 
* reproducible on ... by @vlastahajek 
* not reproducible on `Win10/Qt 5.12.1 MCVC2017 64bit2` (system where I built installer)

**Comment by vlastahajek** [comment]
It is reproducible on **every page**, even short one, just scroll up and down using mouse wheel. 
Tested also on manual build with QT 5.12.0  (Win 10)

**Comment by dvorka** [comment]
Could you please also try AppVeyor artifact e.g. 
https://ci.appveyor.com/project/dvorka/mindforger/builds/22795494/artifacts

**Comment by sbstn87** [comment]
I use latest Windows 10 64bit.

I also confirm that the issue happens also on short pages when scrolling mouse wheel. Previously I did not try to scroll when the whole not was visible.

**Comment by dvorka** [comment]
Hypothesis (unfortunately I'm not able to repro on any of my systems):
* I added mouse wheel zooming (<kbd>Ctrl</kbd>+ mouse wheel) which could be break it.
* ... search web

**Comment by sbstn87** [comment]
Ctrl + mouse wheel does zoom in for me without any issues.

**Comment by dvorka** [comment]
@sbstn87 thanks - this definitely helps!

**Comment by dvorka** [comment]
@sbstn87 does MindForger crashes OR it is frozen (in the latter case it could be an infinite event loop).

@vlastahajek any chance to debug it in Qt Creator (as it's reproducible on your machine)? I also created **branch** `dev/1.49.1` where I removed mouse wheel event hander: https://github.com/dvorka/mindforger/tree/dev/1.49.1 could you please checkout the branch, try to build at... perhaps the problem dissapears 🙏

**Comment by sbstn87** [comment]
It freezes and stops responding until I end the process, while the CPU usage rises strongly.

**Comment by dvorka** [comment]
Great - then it seems like an event loop. Thanks!

**Comment by dvorka** [comment]
@vlastahajek verified that with removal of wheel event handler problem disappears - thank you for that! :clap:

Next steps:
* I will build new distro w/o handler and made it 1.49.0
   * Inability to do <kbd>Ctrl</kdb> + mouse wheel zoom will be know issue (zooming can be controlled from configuration as well).
* I will try to find system where the problem is reproducible or create handler w/o passing wheel event to parent and ask for testing. 
   * Perhaps I can remove forwarding to parent and if it works on my system(s), then it can be way to go forward.
* Fix to go out w/ next version.

@sbstn87 @vlastahajek thank you for your all your help!

**Comment by dvorka** [comment]
I just released MindForger `1.49.1` which is build that I described above - please give it a try: https://github.com/dvorka/mindforger/releases/tag/1.49.0

It should not freeze/crash and Ctrl+mouse wheel should **not** work (but you can use menu Mind/Preferences to set zooming).

**Comment by sbstn87** [comment]
I can confirm that MindForger does not freeze anymore when scrolling. Also, Ctrl + mouse do not zoom in as you mentioned.

**Comment by dvorka** [comment]
:tada: @vlastahajek thanks!

**Comment by dvorka** [comment]
Detailed fix #997 + code review for similar defects is desired.
